### ISSUE TITLE
右侧样式显示不正常，字体乱码

### ISSUE THREAD

**Issue by cksspk** [gezhaoyou/picprose#7]
![CleanShot 2024-04-23 at 14 00 21@2x](https://github.com/gezhaoyou/picprose/assets/37790595/4acb70ad-07c6-40a0-8150-d8f2d53ff9b6)

**Comment by parkergrt** [comment]
浏览器缓存问题，强刷一下，或者无痕模式试试

**Comment by likesrt** [comment]
> 浏览器缓存问题，强刷一下，或者无痕模式试试

确实右侧样式不对 我这边也出现了这种情况

**Comment by parkergrt** [comment]
> > 浏览器缓存问题，强刷一下，或者无痕模式试试
> 
> 确实右侧样式不对 我这边也出现了这种情况

清理缓存有效吗，我用chrome和safari 跑都没问题

**Comment by likesrt** [comment]
> > > 浏览器缓存问题，强刷一下，或者无痕模式试试
> > 
> > 
> > 确实右侧样式不对 我这边也出现了这种情况
> 
> 清理缓存有效吗，我用chrome和safari 跑都没问题

我使用的EDGE浏览器 清理缓存和无痕模式都无效。更换了chrome 也出现了类似问题。
![Clip_2024-04-23_17-36-50](https://github.com/gezhaoyou/picprose/assets/31208912/b923e949-2f4c-4e05-95f2-de6130f28a6e)

**Comment by likesrt** [comment]
> > > 浏览器缓存问题，强刷一下，或者无痕模式试试
> > 
> > 
> > 确实右侧样式不对 我这边也出现了这种情况
> 
> 清理缓存有效吗，我用chrome和safari 跑都没问题

你好 我尝试了使用Vercel 进行部署发现是正确的页面 vercel 首选应该是 yarn install  我本地使用的是 pnpm 下载依赖。是否可能是此原因。   我本地尝试了使用yarn安装依赖 已经恢复正确。 @cksspk
